# Generated by Django 5.1.4 on 2025-01-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_additionalimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
    ]
