# Generated by Django 5.1.4 on 2024-12-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_upvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
