# Generated by Django 5.1.4 on 2024-12-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_options_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
