# Generated by Django 5.1.4 on 2024-12-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
