# Generated by Django 5.1.4 on 2024-12-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
