# Generated by Django 5.1.4 on 2024-12-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_ename_userprofile_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ename',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lname',
        ),
    ]
