# Generated by Django 5.1.4 on 2025-01-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0002_alter_toolbaritem_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolbarExtendedItem',
        ),
    ]
