# Generated by Django 5.1.4 on 2024-12-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0002_alter_toolbaritem_subtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolbaritem',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
