# Generated by Django 5.1.4 on 2024-12-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0003_alter_toolbaritem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
