# Generated by Django 5.1.4 on 2024-12-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0004_toolbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolbar',
            name='external_image_url',
        ),
        migrations.AddField(
            model_name='toolbar',
            name='external_image',
            field=models.ImageField(blank=True, null=True, upload_to='toolbar_images/'),
        ),
    ]
