# Generated by Django 5.1.4 on 2025-01-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0004_remove_toolbaritem_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserChildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='toolbar.usersitem')),
            ],
        ),
    ]
