# Generated by Django 5.1.4 on 2024-12-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0004_toolbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='toolbar.toolbaritem'),
        ),
    ]
