# Generated by Django 5.1.4 on 2024-12-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0005_remove_toolbar_external_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbar',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='toolbar',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='toolbar',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
