# Generated by Django 5.1.4 on 2025-01-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0005_usersitem_userchilditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchilditem',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersitem',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
