# Generated by Django 5.1.4 on 2024-12-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0006_toolbar_name_toolbar_url_toolbar_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolbar',
            old_name='external_image',
            new_name='image',
        ),
    ]
