# Generated by Django 5.1.4 on 2024-12-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0006_feature_delete_toolbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='toolbar_images/')),
                ('url', models.URLField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
