# Generated by Django 5.1.4 on 2025-01-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0006_userchilditem_visible_usersitem_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchilditem',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='toolbar_images/'),
        ),
        migrations.AddField(
            model_name='usersitem',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='toolbar_images/'),
        ),
    ]
