# Generated by Django 5.1.4 on 2024-12-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0007_rename_external_image_toolbar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolbar',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
