# Generated by Django 5.1.4 on 2025-01-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0007_userchilditem_icon_usersitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchilditem',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
