# Generated by Django 5.1.4 on 2025-01-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0007_toolbar_delete_feature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toolbar',
            new_name='ToolbarAd',
        ),
    ]
