# Generated by Django 5.1.4 on 2024-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0008_alter_toolbar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbar',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
