# Generated by Django 5.1.4 on 2025-01-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': [('can_add_group', 'Can add a new group'), ('can_edit_group', 'Can edit a group'), ('can_delete_group', 'Can delete a group')]},
        ),
    ]
