# Generated by Django 5.1.4 on 2025-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_cover_images/'),
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
