# Generated by Django 5.1.4 on 2025-01-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
