# Generated by Django 5.1.4 on 2025-01-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
