# Generated by Django 5.1.4 on 2025-01-05 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'post'], name='likes_like_user_id_e5c92e_idx'),
        ),
    ]
